#!/bin/bash

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

scp ${dir}/build/release/bin/nervad $1:/opt/nerva/nervad
scp ${dir}/build/release/bin/nerva-blockchain-export $1:/opt/nerva/nerva-blockchain-export
scp ${dir}/build/release/bin/nerva-wallet-rpc $1:/opt/nerva/nerva-wallet-rpc

