#!/bin/bash

#Script for dynamic linux builders from the builder repo
#https://bitbucket.org/nerva-project/nerva

#This script can also be used to build from linux directly
#./docker-builder

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source ${dir}/builder/linux-helpers

extractversion
checkdistro
#This would already be done by builder, but run it again in case people are running this script manually
installdeps

mkdir -p ${NERVA_DIR}/build/release
cd ${NERVA_DIR}/build/release

cmake -D CMAKE_BUILD_TYPE=release -D BUILD_SHARED_LIBS=OFF -D BUILD_TESTS=OFF \
	-D BUILD_TAG=${NERVA_BUILD_DISTRO}-${NERVA_BUILD_DISTRO_VERSION} ../..

make -j4
zip -rj ${NERVA_DIR}/nerva-${NERVA_VERSION}_${NERVA_BUILD_DISTRO}-${NERVA_BUILD_DISTRO_VERSION}.zip ${NERVA_DIR}/build/release/bin/*

#clean
cd ${NERVA_DIR}
rm -rf ${NERVA_DIR}/build
find -name CMakeCache.txt | xargs rm
find -name CMakeFiles | xargs rm -rf
find -name *.a | xargs rm
find -name *.o | xargs rm
find -name *.so | xargs rm
