#!/bin/bash

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

datadir=${dir}/db

function n0()
{
	${dir}/builder/build/dev/debug/bin/nervad --stagenet --data-dir ${datadir}/n0 \
	--add-exclusive-node 127.0.0.1:28080 --add-exclusive-node 127.0.0.1:38080 --add-exclusive-node 127.0.0.1:48080 \
	--fixed-difficulty 50 --block-sync-size 1
}

function n1()
{
	${dir}/builder/build/dev/debug/bin/nervad --stagenet --data-dir ${datadir}/n1 --p2p-bind-port 28080 --rpc-bind-port 28081 --zmq-rpc-bind-port 28082 --rpc-restricted-bind-port 28083 \
	--add-exclusive-node 127.0.0.1:38080 --add-exclusive-node 127.0.0.1:48080 --add-exclusive-node 127.0.0.1:19565 \
	--fixed-difficulty 50 --block-sync-size 1 --detach
}

function n2()
{
	${dir}/builder/build/dev/debug/bin/nervad --stagenet --data-dir ${datadir}/n2 --p2p-bind-port 38080 --rpc-bind-port 38081 --zmq-rpc-bind-port 38082 --rpc-restricted-bind-port 38083 \
	--add-exclusive-node 127.0.0.1:28080 --add-exclusive-node 127.0.0.1:48080 --add-exclusive-node 127.0.0.1:19565 \
	--fixed-difficulty 50 --block-sync-size 1 --detach
}

function n3()
{
	${dir}/builder/build/dev/debug/bin/nervad --stagenet --data-dir ${datadir}/n3 --p2p-bind-port 48080 --rpc-bind-port 48081 --zmq-rpc-bind-port 48082 --rpc-restricted-bind-port 48083 \
	--add-exclusive-node 127.0.0.1:28080 --add-exclusive-node 127.0.0.1:38080 --add-exclusive-node 127.0.0.1:19565 \
	--fixed-difficulty 50 --block-sync-size 1 --detach
}

function debug()
{
	killall nervad
	n1
	n2
	n3
}

$1
