#!/bin/bash

BUILDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NERVA_DIR=$(dirname $BUILDER_DIR)
source ${BUILDER_DIR}/environment

detectos
detectversion

export STATIC=ON
export THREAD_COUNT=2
export BUILD_TYPE=release

function build()
{
	aes=$1

	build_dir=${BUILDER_DIR}/output/docker/${BUILD_TYPE}-${aes}

	mkdir -p ${build_dir}
	cd ${build_dir}
	cmake_cmd ${aes}
	make -j${THREAD_COUNT}
}

print_env

build aes
build noaes
