#!/bin/bash
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

BUILDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NERVA_DIR=$(dirname $BUILDER_DIR)

if [ -d "${BUILDER_DIR}/curl" ]; then
	rm -rf "${BUILDER_DIR}/curl"
fi

cd "${NERVA_DIR}/external/curl"

export "CPPFLAGS=-I/mingw32/local/include -O3"
export "LDFLAGS=-L/mingw32/local/lib -mwindows"
export "PKG_CONFIG_PATH=/mingw32/local/lib/pkgconfig"

./configure --prefix="${BUILDER_DIR}/curl" --without-ssl --without-zlib --disable-dict --disable-ftp --disable-gopher \
--disable-file --disable-imap --disable-ldap --disable-ldaps --disable-pop3 --disable-proxy --disable-rtsp --disable-smtp \
--disable-telnet --disable-tftp --disable-smb --disable-smbs --disable-psl --without-brotli --without-nghttp2 \
--without-libidn2 --disable-ftmp --without-libpsl --without-librtmp --enable-static --disable-shared

make -j4
make install-strip

cp ${BUILDER_DIR}/curl/lib/libcurl.a /mingw64/lib/libcurl.a
cp ${BUILDER_DIR}/curl/lib/libcurl.la /mingw64/lib/libcurl.la
cp ${BUILDER_DIR}/curl/lib/pkgconfig/libcurl.pc /mingw64/lib/pkgconfig/libcurl.pc

cp -r ${BUILDER_DIR}/curl/include/curl /mingw64/include
