#!/bin/bash
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

BUILDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NERVA_DIR=$(dirname $BUILDER_DIR)

if [ -d "${BUILDER_DIR}/curl" ]; then
	rm -rf "${BUILDER_DIR}/curl"
fi

cd "${NERVA_DIR}/external/curl"
./buildconf

LIBS="-ldl -lpthread" ./configure --prefix="${BUILDER_DIR}/curl" --without-ssl --without-zlib --disable-dict --disable-ftp --disable-gopher \
--disable-file --disable-imap --disable-ldap --disable-ldaps --disable-pop3 --disable-proxy --disable-rtsp --disable-smtp \
--disable-telnet --disable-tftp --disable-smb --disable-smbs --disable-psl --without-brotli \
--without-libidn2 --disable-ftmp --without-libpsl --without-librtmp --enable-static --disable-shared

make -j4
make install

sudo cp ${BUILDER_DIR}/curl/lib/libcurl.a /usr/local/lib/libcurl.a
sudo cp -r ${BUILDER_DIR}/curl/include/curl /usr/local/include
