#!/bin/bash

BUILDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NERVA_DIR=$(dirname $BUILDER_DIR)
source ${BUILDER_DIR}/environment

detectos
detectversion

if [ ! -f "${BUILDER_DIR}/check_aesni" ]; then
    echo Building the check_aesni tool
    make ${BUILDER_DIR}/check_aesni
fi

${BUILDER_DIR}/check_aesni
aes_supported=$?

build_dir=${BUILDER_DIR}/output/${NERVA_BUILD_OS}/${BUILD_TYPE}

print_env

mkdir -p ${build_dir}
cd ${build_dir}

if [ ${aes_supported} == 1 ]; then
    cmake_cmd aes
else
    cmake_cmd noaes
fi

make -j${THREAD_COUNT}
