#!/bin/bash

BUILDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NERVA_DIR=$(dirname $BUILDER_DIR)

if [ -z ${BUILD_TYPE} ]; then
	export BUILD_TYPE=release
fi

source ${BUILDER_DIR}/environment

detectos
detectversion

build_dir=${BUILDER_DIR}/output/${NERVA_BUILD_OS}/${BUILD_TYPE}

mkdir -p ${build_dir}-aes
cd ${build_dir}-aes
cmake_cmd aes
make -j4

mkdir -p ${build_dir}-noaes
cd ${build_dir}-noaes
cmake_cmd no-aes
make -j4

mv ${build_dir}-aes/bin/nervad ${build_dir}-aes/bin/nervad-aes
mv ${build_dir}-noaes/bin/nervad ${build_dir}-noaes/bin/nervad-noaes

zip -rj ${BUILDER_DIR}/output/nerva-v${NERVA_VERSION}_${NERVA_BUILD_OS}.zip \
	${build_dir}-aes/bin/nervad-aes \
	${build_dir}-noaes/bin/nervad-noaes \
	${build_dir}-aes/bin/nerva-wallet-cli \
	${build_dir}-aes/bin/nerva-wallet-rpc \
	${build_dir}-aes/bin/nerva-quicksync-export \
	${build_dir}-aes/bin/nerva-blockchain-prune \
	${build_dir}-aes/bin/nerva-gen-ssl-cert \
	${build_dir}-aes/bin/nerva-gen-trusted-multisig
