#!/bin/bash

BUILDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NERVA_DIR=$(dirname $BUILDER_DIR)

if [ -z ${BUILD_TYPE} ]; then
	export BUILD_TYPE=debug
fi

source ${BUILDER_DIR}/environment

detectos
detectversion

build_dir=${BUILDER_DIR}/output/${NERVA_BUILD_OS}/${BUILD_TYPE}

mkdir -p ${build_dir}-aes
cd ${build_dir}-aes
cmake_cmd aes
make -j20
