#!/bin/bash

BUILDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NERVA_DIR=$(dirname $BUILDER_DIR)

if [ -z ${BUILD_TYPE} ]; then
	export BUILD_TYPE=release
fi

if [ -z ${STATIC} ]; then
	export STATIC=OFF
fi

if [ -z ${THREAD_COUNT} ]; then
	export THREAD_COUNT=30
fi

if [ -z ${BUILD_EXTRAS} ]; then
	export BUILD_EXTRAS=OFF
fi

function detectos()
{
	if [ "$(uname)" == "Linux" ]; then
		if [[ -z "${NERVA_BUILD_DISTRO}" ]]; then
			local os_distro="unknown"

			if [ -f /etc/os-release ]; then
				source /etc/os-release
				os_distro=$ID
			elif [ -f /etc/lsb-release ]; then
				source /etc/lsb-release
				os_distro=$DISTRIB_ID
			fi
		fi
		export NERVA_BUILD_OS="linux"
		export NERVA_BUILD_DISTRO=${os_distro}
	elif [ "$(uname)" == "Darwin" ]; then
		export NERVA_BUILD_OS="osx"
	elif [ "$(expr substr $(uname -s) 1 7)" == "MSYS_NT" ] || [ "$(expr substr $(uname -s) 1 7)" == "MINGW64" ]; then
		export NERVA_BUILD_OS="windows"
	else
		echo "Unsupported OS"
		exit 0
	fi

	echo OS detected ${NERVA_BUILD_OS} ${NERVA_BUILD_DISTRO}
}

function detectversion()
{
    ver=$(awk '/#define DEF_MONERO_VERSION /{ print $3 }' < ${NERVA_DIR}/src/version.cpp.in)
	name=$(awk '/#define DEF_MONERO_RELEASE_NAME /{ print $3 }' < ${NERVA_DIR}/src/version.cpp.in)
    export NERVA_VERSION=$(echo ${ver} | tr -d '"')
	export NERVA_CODENAME=$(echo ${name} | tr -d '"')
    echo Detected version ${NERVA_VERSION}: ${NERVA_CODENAME}
}

function cmake_cmd()
{
	no_aes=OFF

	if [ "$1" == "aes" ]; then
		no_aes=OFF
	elif [ "$1" == "noaes" ]; then
		no_aes=ON
	else
		echo "Unsupported configuration" $1
		exit 1
	fi
	
	if [ ${NERVA_BUILD_OS} == "linux" ]; then
		cmake -D CMAKE_BUILD_TYPE=${BUILD_TYPE} -D STATIC=${STATIC} -D NO_AES=${no_aes} -D BUILD_TAG=${NERVA_BUILD_OS} -D BUILD_EXTRAS=${BUILD_EXTRAS} ../../../..
	elif [ ${NERVA_BUILD_OS} == "osx" ]; then
		cmake -D CMAKE_BUILD_TYPE=${BUILD_TYPE} -D STATIC=${STATIC} -D NO_AES=${no_aes} -D BUILD_TAG=${NERVA_BUILD_OS} -D BUILD_EXTRAS=${BUILD_EXTRAS} ../../../..
	elif [ ${NERVA_BUILD_OS} == "windows" ]; then
		cmake -D CMAKE_BUILD_TYPE=${BUILD_TYPE} -D STATIC=ON -D NO_AES=${no_aes} -D BUILD_TAG=${NERVA_BUILD_OS} -D BUILD_EXTRAS=${BUILD_EXTRAS} -D ARCH="x86-64" -G "MSYS Makefiles" ../../../..
	else
		echo "Unsupported build platform"
		exit 1
	fi
}

function print_env()
{
	stat="static"
	if [ -z ${STATIC} ] || [ ${STATIC} == "OFF" ]; then
		stat="dynamic"
	fi

	echo Build args: ${BUILD_TYPE} -j${THREAD_COUNT} ${stat}
}

