#!/bin/bash

#For use with the nerva build system
#https://bitbucket.org/nerva-project/nerva

BUILDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NERVA_DIR=$(dirname ${BUILDER_DIR})
source ${BUILDER_DIR}/env
source ${BUILDER_DIR}/helpers
source ${BUILDER_DIR}/linux-helpers

detectversion
detectos

mkdir -p ${BUILDER_DIR}/build/release

cd ${BUILDER_DIR}/build/release
cmake -D CMAKE_BUILD_TYPE=release -D STATIC=ON -D BUILD_TAG=linux-x64 ../../..
make -j4

lscript=${BUILDER_DIR}/build/release/bin/install

#Construct installer script
echo "#!/bin/bash" > $lscript
echo "dir=\"\$(cd \"\$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"" >> $lscript
echo "REPO_NAME="${REPO_NAME} >> $lscript
echo "REPO_NAME_FULL="${REPO_NAME_FULL} >> $lscript
echo "function $(declare -f install)" >> $lscript
echo "install" >> $lscript
chmod +x $lscript

cp ${BUILDER_DIR}/${REPO_NAME}-logo-white.png ${BUILDER_DIR}/build/release/bin/${REPO_NAME}-logo-white.png
cp ${BUILDER_DIR}/${REPO_NAME}-logo-black.png ${BUILDER_DIR}/build/release/bin/${REPO_NAME}-logo-black.png
zip -rj ${NERVA_DIR}/${REPO_NAME}-v${NERVA_VERSION}_linux-x64.zip ${BUILDER_DIR}/build/release/bin/*