#!/bin/bash

function installdeps()
{
    if [ $NERVA_BUILD_DISTRO == "ubuntu" ] || [ $NERVA_BUILD_DISTRO == "debian" ]; then
		sudo apt install -y \
		build-essential cmake pkg-config libboost-all-dev libssl-dev libzmq3-dev libunbound-dev libsodium-dev \
		libminiupnpc-dev libunwind8-dev liblzma-dev libreadline6-dev libldns-dev libexpat1-dev libgtest-dev doxygen graphviz
	elif [ $NERVA_BUILD_DISTRO == "fedora" ]; then
		sudo dnf install -y \
		make automake cmake gcc-c++ boost-devel miniupnpc-devel graphviz \
    	doxygen unbound-devel libunwind-devel pkgconfig cppzmq-devel openssl-devel --setopt=install_weak_deps=False
	else
		echo "This distro is not officially supported"	
		exit 1
	fi
}

function install()
{
	cp ${dir}/${REPO_NAME}* ~/.local/bin
	bdir=$(realpath ~/.local/bin)
	sdir=$(realpath ~/.local/share)

	dfile=${sdir}/applications/${REPO_NAME}d.desktop

	#Construct daemon .desktop file
	echo "[Desktop Entry]" > $dfile
	echo "Name=${REPO_NAME_FULL} Daemon" >> $dfile
	echo "Exec=${REPO_NAME}d" >> $dfile
	echo "Terminal=true" >> $dfile
	echo "Type=Application" >> $dfile
	echo "Icon=${bdir}/${REPO_NAME}-logo-white.png" >> $dfile

	chmod +x $dfile

	wfile=${sdir}/applications/${REPO_NAME}-wallet-cli.desktop

	#Construct wallet .desktop file
	echo "[Desktop Entry]" > $wfile
	echo "Name=${REPO_NAME_FULL} CLI Wallet" >> $wfile
	echo "Exec=${REPO_NAME}-wallet-cli" >> $wfile
	echo "Terminal=true" >> $wfile
	echo "Type=Application" >> $wfile
	echo "Icon=${bdir}/${REPO_NAME}-logo-black.png" >> $wfile

	chmod +x $wfile

	ufile=${bdir}/${REPO_NAME}-uninstall

	#Construct installer script
	echo "#!/bin/bash" > $ufile
	echo "rm ${bdir}/${REPO_NAME}d" >> $ufile
	echo "rm ${bdir}/${REPO_NAME}-wallet-cli" >> $ufile
	echo "rm ${bdir}/${REPO_NAME}-wallet-rpc" >> $ufile
	echo "rm ${bdir}/${REPO_NAME}-blockchain-*" >> $ufile
	echo "rm ${bdir}/${REPO_NAME}-gen-trusted-multisig" >> $ufile
	echo "rm ${bdir}/${REPO_NAME}-logo-*" >> $ufile
	echo "rm ${sdir}/applications/${REPO_NAME}d.desktop" >> $ufile
	echo "rm ${sdir}/applications/${REPO_NAME}-wallet-cli.desktop" >> $ufile
	echo "rm ${bdir}/${REPO_NAME}-uninstall" >> $ufile

	chmod +x $ufile
}
