#!/bin/bash

BUILDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NERVA_DIR=$(dirname $BUILDER_DIR)
source ${BUILDER_DIR}/environment

detectos
detectversion

build_dir=${BUILDER_DIR}/output/${NERVA_BUILD_OS}/${BUILD_TYPE}-aes

print_env

mkdir -p ${build_dir}
cd ${build_dir}
cmake_cmd aes
make -j${THREAD_COUNT}
