#!/bin/bash

BUILDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NERVA_DIR=$(dirname $BUILDER_DIR)
source ${BUILDER_DIR}/helpers

detectos
detectversion

mkdir -p ${BUILDER_DIR}/build/release
cd ${BUILDER_DIR}/build/release
cmake -D CMAKE_BUILD_TYPE=release -D STATIC=ON -D BUILD_TAG="windows" -D ARCH="x86-64" -G "MSYS Makefiles" ../../..
make -j4

zip -rj ${NERVA_DIR}/${REPO_NAME}-v${NERVA_VERSION}_windows.zip ${BUILDER_DIR}/build/release/bin/*
